version: "3.9"

services:

  postgres:
    image: postgres
    container_name: database
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis
    container_name: fsm
    restart: always

  bot:
    build: .
    container_name: bot
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: python run_bot.py