version: "3.9"

networks:
  bot:

services:

  postgres:
    image: postgres:14
    container_name: database
    restart: unless-stopped
    volumes:
      - ./database/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - bot

  redis:
    image: redis
    container_name: fsm
    restart: unless-stopped
    networks:
      - bot

  bot:
    build: .
    container_name: bot
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    command: python run_bot.py
    networks:
      - bot